# Generated by Django 4.2.4 on 2023-08-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsbackend', '0002_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
