# Generated by Django 4.2.4 on 2023-08-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsbackend', '0005_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuário', to='jsbackend.tipo_usuario')),
            ],
        ),
    ]
