# Generated by Django 4.2.4 on 2023-08-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsbackend', '0007_compra_itenscompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='movel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moveis', to='jsbackend.movel'),
        ),
    ]
