# Generated by Django 4.2.4 on 2023-08-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('jsbackend', '0008_alter_itenscompra_movel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movel',
            options={'verbose_name': 'Móvel', 'verbose_name_plural': 'Móveis'},
        ),
        migrations.AddField(
            model_name='movel',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
