# Generated by Django 4.2.5 on 2023-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsbackend', '0010_cliente_remove_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipousuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Cliente'), (2, 'Gerente'), (3, 'Funcionário')], default=1),
        ),
    ]
