# Generated by Django 4.2.5 on 2023-09-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsbackend', '0011_remove_usuario_tipousuario_usuario_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Tipo_Usuario',
        ),
    ]
