# Generated by Django 4.2.5 on 2023-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsbackend', '0012_delete_cliente_delete_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='material',
        ),
        migrations.AddField(
            model_name='movel',
            name='cor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
